version: "3.8"

services:
  database:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
    network_mode: "host"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    volumes:
      - ./server:/server
      - /server/node_modules
    network_mode: "host"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
      - /client/node_modules
    network_mode: "host"
    # The client process exists immediately if STDIN is not open.
    # See: https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
