name: Pull request check for client

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: client

jobs:
  test_client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: client
        run: npm i

      - name: Run ESlint
        run: npx eslint .
